name:                 vendas
version:              1.0.0
visibility:           public
id:                   vendas-1.0.0-inplace
key:                  vendas-1.0.0-inplace
abi:                  inplace
exposed:              True
exposed-modules:      Vendas
import-dirs:
    /home/clara/programacao-funcional/praticas/p02/2024-2_A02-vendas-MCMMoreira-main/dist-newstyle/build/x86_64-linux/ghc-9.4.8/vendas-1.0.0/build

library-dirs:
    /home/clara/programacao-funcional/praticas/p02/2024-2_A02-vendas-MCMMoreira-main/dist-newstyle/build/x86_64-linux/ghc-9.4.8/vendas-1.0.0/build

library-dirs-static:
    /home/clara/programacao-funcional/praticas/p02/2024-2_A02-vendas-MCMMoreira-main/dist-newstyle/build/x86_64-linux/ghc-9.4.8/vendas-1.0.0/build

dynamic-library-dirs:
    /home/clara/programacao-funcional/praticas/p02/2024-2_A02-vendas-MCMMoreira-main/dist-newstyle/build/x86_64-linux/ghc-9.4.8/vendas-1.0.0/build

data-dir:
    /home/clara/programacao-funcional/praticas/p02/2024-2_A02-vendas-MCMMoreira-main/.

hs-libraries:         HSvendas-1.0.0-inplace
depends:              Cabal-syntax-3.8.1.0 base-4.17.2.1
haddock-interfaces:
    /home/clara/programacao-funcional/praticas/p02/2024-2_A02-vendas-MCMMoreira-main/dist-newstyle/build/x86_64-linux/ghc-9.4.8/vendas-1.0.0/doc/html/vendas/vendas.haddock

haddock-html:
    /home/clara/programacao-funcional/praticas/p02/2024-2_A02-vendas-MCMMoreira-main/dist-newstyle/build/x86_64-linux/ghc-9.4.8/vendas-1.0.0/doc/html/vendas
